package tech.subluminal.shared.records;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * Represents a player lobby on the server.
 */
public class Lobby extends SlimLobby {

  private Map<String, Boolean> users = new HashMap<>();
  //TODO: Make lobbies password protected
  //private boolean pwProtected;
  //private String password;

  // Game Settings
  private double gameSpeed = 1.0f;
  private double mapSize = 2.0f;

  /**
   *
   * @param id is the ID of the lobby (generated by the lobby manager).
   * @param name is the common name of the lobby.
   * @param adminID points to the user who has created the lobby and can change its settings.
   */
  public Lobby(String id, String name, String adminID) {
    super(id, name, adminID);
    users.put(adminID, false);
    //this.pwProtected = false;
    //this.password = null;
  }

  public void addPlayer(String id) {
    users.put(id, false);
  }

  public void removePlayer(String id) {
    users.remove(id);
  }

  public int getPlayerCount() {
    return users.size();
  }

  public double getGameSpeed() {
    return gameSpeed;
  }

  public void setGameSpeed(double gameSpeed) {
    this.gameSpeed = gameSpeed;
  }

  public double getMapSize() {
    return mapSize;
  }

  public void setMapSize(double mapSize) {
    this.mapSize = mapSize;
  }

  public Set<String> getPlayers() {
    return users.keySet();
  }

}
