FROM subluminalthegame/gradle:4.6.0-jdk8-openjfx-alpine

ARG VERSION=unknown
ARG PORT=1729
ENV VERSION=$VERSION
ENV PORT=$PORT

LABEL projectname="Subluminal - The Game"
LABEL company="Bordeaux Ink."
LABEL maintainer="Luc Kury <luc.kury@unibas.ch>"
LABEL version=$VERSION

WORKDIR /opt/lib/subluminal
ADD ./app/build/libs/Subluminal-$VERSION.jar /opt/lib/subluminal
EXPOSE $PORT

ENTRYPOINT java -jar Subluminal-$VERSION.jar server $PORT
CMD [--loglevel=info --logfile=log/log.txt]