FROM openjdk:8u151-jre-alpine3.7

LABEL projectname="Subluminal - The Game"
LABEL company="Bordeaux Ink."
LABEL maintainer="Luc Kury <luc.kury@unibas.ch>"

WORKDIR /opt/lib/subluminal
ADD ./app/build/libs/Subluminal-0.3.0-beta1.jar /opt/lib/subluminal
EXPOSE 1790

ENTRYPOINT ["java", "-jar", "Subluminal-0.3.0-beta1.jar", "server", "1729"]